config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :likes
  post 'likes/check_delete'
  get 'admin/genres'
  post 'admin/genre_delete'
  post 'admin/genre_add'
  post 'admin/genre_update'
  post 'admin/publisher_delete'
  post 'admin/publisher_add'
  post 'admin/publisher_update'
  get 'admin/publishers'
  get 'admin/games_in'
  get 'admin/create_game'
  post 'admin/game_delete'
  get 'admin/users'
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/genre_top'
  
  get 'home_page/index'
  get 'home_page/genre_top'

  resources :review_comments

  resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :games
  resources :genres
  resources :publishers
  devise_for :users, controllers: {
      registrations: 'users/registrations',
  }
  resources :users, except: [:edit] do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resource  :notifications, only: [:update] do
    post "seen_notification"
  end
  root :to => "home_page#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'rates' => 'rate#index'
  post 'rate' => 'rate#update'
  post 'search' => 'search#search'

  # for notifications
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    default_url_options :host => "localhost:3000"
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @c_game = Game.all.count
    @c_review = Review.all.count
    @c_genre = Genre.all.count
    
    if @c_review < 10 
      @last_reviews = Review.all
    else
      @last_reviews = Review.last(10)
    end
    @genres = Genre.all
    # @genre_review_tops = Genre.find(1).games
    #get point and review_id to hash @points
    @games = Game.all
    @reviews = Review.all
    if @c_review > 5
      @points = Hash.new
      @reviews.each do |review|
          @points[review.id] = ReviewComment.where(review_id: review.id).count
      end
      @points = @points.sort_by{|k,v| -v}
      @review_1st = Review.find(@points.first[0])
      @review_4ths = []
      (1..4).each  do |i|
        id = @points.at(i)[0]
        review = Review.find(id)
      @review_4ths << review
      end
      @points = @points.to_h
    end
    #get hot review by genre
    @c_check = 0
    if @c_review>=5 && @c_genre > 2
      @genre_points = Hash.new
      @genre_games = Genre.all.first.games
      @genre_games.each do |game|
        @genre_reviews = Review.where(game_id: game.id)
        @genre_reviews.each do |review|
          @genre_points[review.id] = ReviewComment.where(review_id: review.id).count
      end
      end
      @genre_points = @genre_points.sort_by{|k,v| -v}
      @genre_review_tops = []
      # @c_check = Review.where(review_id: review.id).count
      if @genre_points.length >=5
        @c_check = 1
        (0..4).each  do |i|
          id = @genre_points.at(i)[0]
          review = Review.find(id)
        @genre_review_tops << review
        end
      end
      @genre_points = @genre_points.to_h
    end
  end
  
  def genre_top
    @genre_points = Hash.new
    @genre_games = Genre.find(params[:genre]).games
    @genre_games.each do |game|
      @genre_reviews = Review.where(game_id: game.id)
      @genre_reviews.each do |review|
        @genre_points[review.id] = ReviewComment.where(review_id: review.id).count
    end
    end
    puts params[:genre]
    @genre_points = @genre_points.sort_by{|k,v| -v}
    @genre_review_tops = []
    (0..4).each  do |i|
      puts @genre_points.at(i)[0]
      review = Review.find(@genre_points.at(i)[0])
      game = Game.find(review.game_id)
      if game.photo == nil 
         review.photo = game.photo
      else
         review.photo = game.image
      end
      puts "aaa"
      puts game.image
      @genre_review_tops << review
    end
    @genre_points = @genre_points.to_h
    if request.xhr?
      respond_to do |format|
      format.json {
        render json: {genre_review_tops: @genre_review_tops}
      }
    end
    end
  end
end

app/views/home_page/index.html.erb
<div class="container">
  <div class="container row span12 promo--header"><h1>Reviews</h1></div>
  <% if @c_review >= 5 %>
  <section class="promo--container container row span12  js-impression-tracking " data-impression-tracking="">
    <a  href=<%= review_url(@review_1st) %>
            class="promo--object promo-type--single  js-event-tracking">
    <div class="col-md-8 promo--image promo--wide promo--offset-wide">
      <div content">
        <%if @review_1st.game.photo==nil %>
          <%= image_tag @review_1st.photo || "yasuo.jpg", class:"img-responsive"%>
        <% else %>
            <%= image_tag @review_1st.photo || "yasuo.jpg", class:"img-responsive"%>
        <% end %>
      </div>
    </div>
    <div class="col-md-4 promo--offset-square promo--square promo--single-metadata">
      <div class="content">
        <div class="promo--media-type ">
          <div class="content">
            <div class="promo--review-score circle circle-big text-center"><%= @points[@review_1st.id] %></div>
          </div>
        </div>
        <summary class="promo--metadata">
          <h2 class="text-bold text-color-primary"><%= @review_1st.title %></h2>
          <span class="text-simple"><%= raw @review_1st.content.truncate(150)%></span>
        </summary>
      </div>
    </div>
    </a>
  </section>
  
  <div class="row promo-strip-list">
    <% @review_4ths.each do |r| %>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 slide-item-game">
          <a href="/reviews/<%=r.id%>">
            <div class="panel panel-default">
              <%if r.game.photo==nil %>
                  <%= image_tag r.game.photo || "yasuo.jpg", class:"display-center"%>
              <% else %>
                  <%= image_tag r.game.photo || "yasuo.jpg", class:"display-center"%>
              <% end %>
            </div>
            <div class="circle circle-small text-center col-md-3"><%= @points[r.id] %></div>
            <h4 class="col-md-9 text-bold hover-primary"><%=r.title%></h4>
          </a>
        </div>
    <% end %>
  </div>
<% end %>

  <div class="row">
    <div class="col-md-8 content-latest">
      <div class="pod-header">
        <div class="pod-header-item col-md-4">
          <div class="pod-title">
            <h4 class="text-bold"><span class="glyphicon glyphicon-fire"></span> Latest Reviews</h4>
          </div>
        </div>
        <span class="col-md-8"><hr></hr></span>
      </div>
      <div class="media-game-list">
        <% if @c_review >=2  %>
        <% @last_reviews.each do |last_review| %>
            <div class="media-game">
              <a class="media-game-item">
                <div class="col-md-4 media-figure media-figure--medium">
                  <div class="media-img imgflare--boxart">
                    <%if last_review.game.photo==nil %>
                      <%= image_tag last_review.game.photo || "yasuo.jpg" %>
                    <% else %>
                      <%= image_tag last_review.game.photo || "yasuo.jpg" %>
                    <% end %>
                  </div>
                </div>
                <div class="col-md-7 media-content">
                  <a href="<%= review_url(last_review) %>" class="text-bold media-content-title"><%=last_review.title%></a>
                  <div><span class="media-content-pre">Game: </span><a href=<%= game_url(last_review.game) %> class="media-content-des"><%=last_review.game.name%></a></div>
                  <div><span class="media-content-pre">Review by: </span><a href=<%= user_url(last_review.user) %> class="media-content-des"><%=last_review.user.name%></a></div>
                  <div class="media-content-detail"><span><%= truncate(last_review.content, length: 280)%></span></div>
                  <small class="time-ago"><%= time_ago_in_words last_review.created_at %></small>
                </div>
                <div class="circle circle-big text-center col-md-1">
                  <%= @points[last_review.game.id] %>
                </div>
              </a>
            </div>
            <div class="site-hr"><hr></hr></div>
        <% end %>
        <a class="more-info col-md-offset-10" href="<%= reviews_path %>">Read more ></a>
        <% else %>
          <h3></h3>
      <% end %>
      </div>
    </div>


    <div class="col-md-4">
      <div class="pod-header">
        <div class="pod-header-item col-md-8">
          <div class="pod-title">
            <h4 class="text-bold"><span class="glyphicon glyphicon-heart"></span> Top Reviews</h4>
          </div>
        </div>
        <span class="col-md-4"><hr></hr></span>
      </div>
      <% if @c_review>=5 && @c_genre >=2 %>
      <div class="pod-body">
        <article class="media media-is-top"></article>
        <div class="input-field col-md-12">
          <%= form_tag do %>
              <div id="select-genre-top">
                <%= select_tag :genre, options_for_select(@genres.collect{|g| [g.name, g.id]}, selected: params[:genre]), id: "genre-select", class: "form-control" %>
              </div>
          <% end %>
          <% if @c_check == 1 %>
          <div id="games-genre-top">
            <div class="row" id="game-top-display">
              <% if @genre_review_tops.any? %>
                  <% @genre_review_tops.each do |top| %>
                      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="panel panel-default">
                          <a href=<%= review_url(top) %> >
                            <%if top.game.photo==nil %>
                                <%= image_tag top.game.photo || "yasuo.jpg", class: "display-center" %>
                            <% else %>
                              <%= image_tag top.game.photo || "yasuo.jpg", class: "display-center" %>
                            <% end %>
                          </a>
                        </div>
                      </div>
                      <div class="col-md-6 genre-top-name text-bold"><a href=<%= review_url(top) %>><%= top.title %></a></div>
                      <div class="media-content-detail-small">
                      <span>
                        <%= raw top.content.truncate(150)%>
                      </span>
                      </div>
                      <div class="top-hr"><hr/></div>
                  <% end %>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <% else %>
      <h4>No data to display!</h4>
      <% end %>
    </div>
  </div>