config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :likes
  post 'likes/check_delete'
  get 'admin/genres'
  post 'admin/genre_delete'
  post 'admin/genre_add'
  post 'admin/genre_update'
  post 'admin/publisher_delete'
  post 'admin/publisher_add'
  post 'admin/publisher_update'
  get 'admin/publishers'
  get 'admin/games_in'
  get 'admin/create_game'
  post 'admin/game_delete'
  get 'admin/users'
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/genre_top'
  
  get 'home_page/index'
  get 'home_page/genre_top'

  resources :review_comments

  resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :games
  resources :genres
  resources :publishers
  devise_for :users, controllers: {
      registrations: 'users/registrations',
  }
  resources :users, except: [:edit] do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resource  :notifications, only: [:update] do
    post "seen_notification"
  end
  root :to => "home_page#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'rates' => 'rate#index'
  post 'rate' => 'rate#update'
  post 'search' => 'search#search'

  # for notifications
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    default_url_options :host => "localhost:3000"
  end
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  after_create_commit {
    # send notification to Review's owner
    if self.user.id != self.review.user.id
      @notification = Notification.new(
          from_user_id: self.user.id,
          to_user_id: self.review.user.id,
          type: Notification.types[:comment],
          review_id: self.review_id,
          status: Notification.statuses[:not_seen],
          text: self.content
      )
      @notification.save
    end

    # send notifications to all commented Users
    @users = self.review.review_comments.all.collect(&:user).uniq.reject{|user| user.id == self.review.user.id || user.id == self.user.id}
    @users.each do |user|
      @notification = Notification.new(
          from_user_id: self.user.id,
          to_user_id: user.id,
          type: Notification.types[:comment_on_same_review],
          review_id: self.review_id,
          status: Notification.statuses[:not_seen],
          text: self.content
      )
      @notification.save
    end
  }
end

app/controllers/review_comments_controller.rb
class ReviewCommentsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_review_comment, only: [:show, :edit, :update, :destroy]

  # GET /review_comments
  # GET /review_comments.json
  def index
    @review_comments = ReviewComment.all
  end

  # GET /review_comments/1
  # GET /review_comments/1.json
  def show
  end

  # GET /review_comments/new
  def new
    @review_comment = ReviewComment.new
  end

  # GET /review_comments/1/edit
  def edit
  end

  # POST /review_comments
  # POST /review_comments.json
  def create
    @review_comment = ReviewComment.new(review_comment_params)
    @review_comment.user_id = current_user.id

    respond_to do |format|
      if @review_comment.save
        url = "/reviews/" + @review_comment.review_id.to_s
        format.html { redirect_to url, notice: 'Review comment was successfully created.' }
        #format.html { redirect_to @review_comment, notice: 'Review comment was successfully created.' }
        format.json { render :show, status: :created, location: @review_comment }
      else
        format.html { render :new }
        format.json { render json: @review_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /review_comments/1
  # PATCH/PUT /review_comments/1.json
  def update
      @review_comment.update(review_comment_params)
  end

  # DELETE /review_comments/1
  # DELETE /review_comments/1.json
  def destroy
    @review_comment.destroy
    respond_to do |format|
      url = "/reviews/" + @review_comment.review_id.to_s
      format.html { redirect_to url, notice: 'Review comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review_comment
      @review_comment = ReviewComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_comment_params
      params.require(:review_comment).permit(:user_id, :review_id, :content)
    end
end

app/helpers/review_comments_helper.rb
module ReviewCommentsHelper
    def self.point_avg(id)
        @total = ReviewComment.find(id).size
        @total = RateTable.where(game_id: id).count

        @star_1 = RateTable.where(game_id: id, point: 1).count
        @star_2 = RateTable.where(game_id: id, point: 2).count
        @star_3 = RateTable.where(game_id: id, point: 3).count
        @star_4 = RateTable.where(game_id: id, point: 4).count
        @star_5 = RateTable.where(game_id: id, point: 5).count
        total_point = @star_1 + 2*@star_2 + 3*@star_3 + 4*@star_4 + 5*@star_5
        if @total==0
          @point_avg = 0
        else
          @point_avg = (100*total_point/@total).round / 100.0
        end
        return @point_avg
    end
end

app/views/review_comments/_form.html.erb
<%= form_with(model: review_comment, local: true) do |form| %>
  <% if review_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review_comment.errors.count, "error") %> prohibited this review_comment from being saved:</h2>

      <ul>
      <% review_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :review_comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :review_id %>
    <%= form.number_field :review_id, id: :review_comment_review_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :review_comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/review_comments/edit.html.erb
<h1>Editing Review Comment</h1>

<%= render 'form', review_comment: @review_comment %>

<%= link_to 'Show', @review_comment %> |
<%= link_to 'Back', review_comments_path %>

app/views/review_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Review Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Review</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @review_comments.each do |review_comment| %>
      <tr>
        <td><%= review_comment.user_id %></td>
        <td><%= review_comment.review_id %></td>
        <td><%= review_comment.content %></td>
        <td><%= link_to 'Show', review_comment %></td>
        <td><%= link_to 'Edit', edit_review_comment_path(review_comment) %></td>
        <td><%= link_to 'Destroy', review_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review Comment', new_review_comment_path %>

app/views/review_comments/new.html.erb
<h1>New Review Comment</h1>

<%= render 'form', review_comment: @review_comment %>

<%= link_to 'Back', review_comments_path %>

app/views/review_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review_comment.user_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review_comment.review_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review_comment.content %>
</p>

<%= link_to 'Edit', edit_review_comment_path(@review_comment) %> |
<%= link_to 'Back', review_comments_path %>