config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :likes
  post 'likes/check_delete'
  get 'admin/genres'
  post 'admin/genre_delete'
  post 'admin/genre_add'
  post 'admin/genre_update'
  post 'admin/publisher_delete'
  post 'admin/publisher_add'
  post 'admin/publisher_update'
  get 'admin/publishers'
  get 'admin/games_in'
  get 'admin/create_game'
  post 'admin/game_delete'
  get 'admin/users'
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/genre_top'
  
  get 'home_page/index'
  get 'home_page/genre_top'

  resources :review_comments

  resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :games
  resources :genres
  resources :publishers
  devise_for :users, controllers: {
      registrations: 'users/registrations',
  }
  resources :users, except: [:edit] do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resource  :notifications, only: [:update] do
    post "seen_notification"
  end
  root :to => "home_page#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'rates' => 'rate#index'
  post 'rate' => 'rate#update'
  post 'search' => 'search#search'

  # for notifications
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    default_url_options :host => "localhost:3000"
  end
end

app/views/admin/_navigation.html.erb
<div class="row">
    <nav class="navbar navbar-findcond navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
          <%= link_to "ゲームセンター", root_path, :class => "navbar-brand" %>
        </div>
		<div class="collapse navbar-collapse" id="navbar">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#"><%= link_to('My Profile', user_path(current_user.id)) %></a></li>
						<li class="divider"></li>
                        <li><a href="#"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
</div>


<div class="row" style="padding-top:50px">
    <!-- uncomment code for absolute positioning tweek see top comment in css -->
    <!-- <div class="absolute-wrapper"> </div> -->
    <!-- Menu -->
    <div class="side-menu">
    
    <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <div class="brand-wrapper">
            <!-- Hamburger -->
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Brand -->
            <div class="brand-name-wrapper">
                <a class="navbar-brand" href="#">
                    Search
                </a>
            </div>

            <!-- Search -->
            <a data-toggle="collapse" href="#search" class="btn btn-default" id="search-trigger">
                <span class="glyphicon glyphicon-search"></span>
            </a>

            <!-- Search body -->
            <div id="search" class="panel-collapse collapse">
                <div class="panel-body">
                    <form class="navbar-form" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default "><span class="glyphicon glyphicon-ok"></span></button>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- Main Menu -->
    <div class="side-menu-container">
        <ul class="nav navbar-nav">

            <li><a href=<%= admin_dashboard_path %>><span class="glyphicon glyphicon-signal"></span> Dashboard</a></li>
            <li><a href=<%= admin_genres_path %>><span class="glyphicon glyphicon-tags"></span> Genres</a></li>
            <li><a href=<%= admin_publishers_path %>><span class="glyphicon glyphicon-list-alt"></span> Publishers</a></li>
            <li><a href=<%= admin_games_path %>><span class="glyphicon glyphicon-send"></span> Games</a></li>
            <li><a href=<%= admin_users_path %>><span class="glyphicon glyphicon-send"></span> Users</a></li>
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
    
    </div>

    <!-- Main Content -->
    <div class="container-fluid">
        <div class="side-body">
         <%= yield %>
        </div>
    </div>
</div>

<script>
    $(function () {
    $('.navbar-toggle').click(function () {
        $('.navbar-nav').toggleClass('slide-in');
        $('.side-body').toggleClass('body-slide-in');
        $('#search').removeClass('in').addClass('collapse').slideUp(200);

        /// uncomment code for absolute positioning tweek see top comment in css
        //$('.absolute-wrapper').toggleClass('slide-in');
        
    });
   
   // Remove menu for searching
   $('#search-trigger').click(function () {
        $('.navbar-nav').removeClass('slide-in');
        $('.side-body').removeClass('body-slide-in');

        /// uncomment code for absolute positioning tweek see top comment in css
        //$('.absolute-wrapper').removeClass('slide-in');

    });
});
</script>

app/views/admin/create_game.html.erb
<%= render 'games/form', game: @game %>

app/views/admin/dashboard.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <h1>Dashboard</h1>
	<div class="row col-md-12">
      <div class="col-md-4 col-md-offset-1">
        <div class="panel panel-info">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-6">
                <i class="fa fa-tags fa-5x"></i>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading"><%= @count_genres %></p>
                <p class="announcement-text">Genres</p>
              </div>
            </div>
          </div>
          <a>
            <div class="panel-footer announcement-bottom">
              <div class="row">
                <div class="col-xs-6">
                  <%= link_to "More info", admin_genres_path %>
                </div>
                <div class="col-xs-6 text-right">
                  <i class="fa fa-arrow-circle-right"></i>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="panel panel-success">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-6">
                <i class="fa fa-list-alt fa-5x"></i>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading"><%= @count_puplishers %></p>
                <p class="announcement-text"> Publishers</p>
              </div>
            </div>
          </div>
          <a>
            <div class="panel-footer announcement-bottom">
              <div class="row">
                <div class="col-xs-6">
                 <%= link_to "More info", admin_publishers_path %>
                </div>
                <div class="col-xs-6 text-right">
                  <i class="fa fa-arrow-circle-right"></i>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div><!-- /.row -->
    
    <div class="row col-md-12">
      <div class="col-md-4 col-md-offset-1">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-6">
                <i class="fa fa-send fa-5x"></i>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading"><%= @count_games %></p>
                <p class="announcement-text">Games</p>
              </div>
            </div>
          </div>
          <a>
            <div class="panel-footer announcement-bottom">
              <div class="row">
                <div class="col-xs-6">
                  <%= link_to "More info", admin_games_path %>
                </div>
                <div class="col-xs-6 text-right">
                  <i class="fa fa-arrow-circle-right"></i>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-6">
                <i class="fa fa-comments fa-5x"></i>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading"><%= @count_reviews %></p>
                <p class="announcement-text"> Reviews</p>
              </div>
            </div>
          </div>
          <a>
            <div class="panel-footer announcement-bottom">
              <div class="row">
                <div class="col-xs-6">
                 <%= link_to "More info", "" %>
                </div>
                <div class="col-xs-6 text-right">
                  <i class="fa fa-arrow-circle-right"></i>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div><!-- /.row -->
    </div>

app/views/admin/edit_game.html.erb
<h1>Editing Game</h1>

<%= render '/games/form', game: @game %>

app/views/admin/games.html.erb
<!--<div class="container">-->
    <h1>Games</h1>
    <div class="row col-md-12 custyle">
    <table id="table-genre" class="table table-striped custab table-hover table-bordered table-list">
    <thead>
    <a class="btn btn-primary pull-right genre-add" href="<%= admin_create_game_path %>"><b>+</b> Add new Games</a>
        <tr>
            <th class="5-area">ID</th>
            <th class="20-area">Image</th>
            <th class="10-area">Name</th>
            <th class="10-area">Publishers</th>
            <th class="10-area">Genres</th>
            <th class="10-area">Story</th>
            <th class="10-area">Guide</th>
            <th class="15-area">Description</th>
            <th class="text-center 10-area">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @games.each do |game| %>
            <tr id="row-<%= game.id %>">
                <td><%= game.id %></td>
                <td>
                    <div class="image-game">
                        <%= image_tag game.photo || "yasuo.jpg" , id: "new_photo" %>
                    </div>
                </td>
                <td class="genre-name-<%= game.id%>"><%= game.name%></td>
                <td>
                </td>
                <td>
                    <% game.genres.each do |g| %>
                    <%= g.name%> ,
                    <% end %>
                </td>
                <td><%= truncate(game.story, length: 100)%></td>
                <td><%= truncate(game.guide, length: 100)%></td>
                <td><%= truncate(game.description, length: 100)%></td>
                <td class="text-center genre-edit" value=<%= game.id%>>
                    <a class='btn btn-info btn-xs genre-edit'><span class="glyphicon glyphicon-edit"></span></a>
                    <a class='btn btn-danger btn-xs genre-delete'><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
<!--</div>-->

<script>
    $('.genre-delete').on('click', function() {
    // $(".genre-delete").click(function(event){
        var game_id =  $(this).parent().attr('value');
        console.log(game_id);
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this data!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    url: "/admin/game_delete",
                    method: "POST",
                    dataType: "json",
                    data: {game_id: game_id},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not delete!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        console.log(response);
                        swal("Poof! Your data has been deleted!", {
                            icon: "success",
                    });
                     $("#row-"+game_id).remove();
                    }
                });
            }
    });
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

app/views/admin/genres.html.erb
    <h1>Genres</h1>
    <div class="row col-md-12 custyle">
    <table id="table-genre" class="table table-striped custab table-hover table-bordered table-list">
    <thead>
    <a class="btn btn-primary pull-right genre-add"><b>+</b> Add new Genres</a>
        <tr>
            <th class="id-area">ID</th>
            <th class="name-area">Name</th>
            <th class="text-center edit-area">Edit</th>
            <th class="text-center delete-area">Delete</th>
        </tr>
    </thead>
    <tbody>
        <% @genres.each do |genre| %>
            <tr id="row-<%= genre.id %>">
                <td><%= genre.id %></td>
                <td class="genre-name-<%= genre.id%>"><%= genre.name%></td>
                <td class="text-center genre-edit" value=<%= genre.id%>><a class='btn btn-info btn-xs'><span class="glyphicon glyphicon-edit"></span> Edit</a> </td>
                <td class="text-center genre-delete" value=<%= genre.id%>><a class='btn btn-danger btn-xs'><span class="glyphicon glyphicon-remove"></span> Delete</a> </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
    
<script>
    $('#table-genre').on('click', '.genre-delete', function() {
    // $(".genre-delete").click(function(event){
        var genre_id =  $(this).attr('value');
        console.log(genre_id);
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this data!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    url: "/admin/genre_delete",
                    method: "POST",
                    dataType: "json",
                    data: {genre_id: genre_id},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not delete!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        console.log(response);
                        swal("Poof! Your data has been deleted!", {
                            icon: "success",
                    });
                     $("#row-"+genre_id).remove();
                    }
                });
            }
    });
    });
    
    $(".genre-add").click(function(event){
        swal({
            text: 'Input a genre. e.g. "Action",...',
            content: "input",
            button: {
                text: "Add to Genres",
                closeModal: false,
            },
        }).then((value) => {
            if (value) {
                $.ajax({
                    url: "/admin/genre_add",
                    method: "POST",
                    dataType: "json",
                    data: {genre_name: value},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not add!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        var genre = response["genre"];
                        console.log(genre);
                        swal("Genres has been added!", {
                            icon: "success",
                        });

                        $('table > tbody > tr:first').before(
                            '<tr id="row-'+ genre["id"] + '">' +
                            '<td>' + genre["id"] + '</td>' +
                            '<td>' + genre["name"] + '</td>' +
                            '<td class="text-center genre-edit" value=' + genre["id"] +'><a class="btn btn-info btn-xs"><span class="glyphicon glyphicon-edit"></span> Edit</a> </td>' +
                            '<td class="text-center genre-delete" value=' + genre["id"] +'><a class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a> </td>' +
                            '</tr>'
                        );
                    }
                });

            }
        });
    });

    $('#table-genre').on('click', '.genre-edit', function() {
    // $(".genre-edit").click(function(event){
        var genre_id =  $(this).attr('value');
        swal({
            text: 'Input a new name of genre. e.g. "Action",...',
            content: "input",
            button: {
                text: "Edit Genre",
                cancel: "Cancel",
                closeModal: false,
            },
        }).then((value) => {
            if (value) {
                $.ajax({
                    url: "/admin/genre_update",
                    method: "POST",
                    dataType: "json",
                    data: {genre_name: value, genre_id: genre_id},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not add!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        swal("Genres has been updated!", {
                            icon: "success",
                        });
                        $(".genre-name-"+ genre_id).text(value);
                    }
                });

            }
        });
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

app/views/admin/publishers.html.erb
<!--<div class="container">-->
    <h1>Publishers</h1>
    <div class="row col-md-12 custyle">
    <table id="table-genre" class="table table-striped custab table-hover table-bordered table-list">
    <thead>
    <a class="btn btn-primary pull-right genre-add"><b>+</b> Add new Publishers</a>
        <tr>
            <th class="id-area">ID</th>
            <th class="name-area">Name</th>
            <th class="text-center edit-area">Edit</th>
            <th class="text-center delete-area">Delete</th>
        </tr>
    </thead>
    <tbody>
        <% @publishers.each do |publisher| %>
            <tr id="row-<%= publisher.id %>">
                <td><%= publisher.id %></td>
                <td class="genre-name-<%= publisher.id%>"><%= publisher.name%></td>
                <td class="text-center genre-edit" value=<%= publisher.id%>><a class='btn btn-info btn-xs'><span class="glyphicon glyphicon-edit"></span> Edit</a> </td>
                <td class="text-center genre-delete" value=<%= publisher.id%>><a class='btn btn-danger btn-xs'><span class="glyphicon glyphicon-remove"></span> Delete</a> </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
<!--</div>-->

<script>
    $('#table-genre').on('click', '.genre-delete', function() {
    // $(".genre-delete").click(function(event){
        var publisher_id =  $(this).attr('value');
        console.log(publisher_id);
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this data!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    url: "/admin/publisher_delete",
                    method: "POST",
                    dataType: "json",
                    data: {publisher_id: publisher_id},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not delete!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        console.log(response);
                        swal("Poof! Your data has been deleted!", {
                            icon: "success",
                    });
                     $("#row-"+publisher_id).remove();
                    }
                });
            }
    });
    });
    
    $(".genre-add").click(function(event){
        swal({
            text: 'Input a genre. e.g. "Action",...',
            content: "input",
            button: {
                text: "Add to Genres",
                closeModal: false,
            },
        }).then((value) => {
            if (value) {
                $.ajax({
                    url: "/admin/publisher_add",
                    method: "POST",
                    dataType: "json",
                    data: {publisher_name: value},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not add!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        var publisher = response["publisher"];
                        console.log(publisher);
                        swal("Genres has been added!", {
                            icon: "success",
                        });

                        $('table > tbody > tr:first').before(
                            '<tr id="row-'+ publisher["id"] + '">' +
                            '<td>' + publisher["id"] + '</td>' +
                            '<td>' + publisher["name"] + '</td>' +
                            '<td class="text-center genre-edit" value=' + publisher["id"] +'><a class="btn btn-info btn-xs"><span class="glyphicon glyphicon-edit"></span> Edit</a> </td>' +
                            '<td class="text-center genre-delete" value=' + publisher["id"] +'><a class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a> </td>' +
                            '</tr>'
                        );
                    }
                });

            }
        });
    });

    $('#table-genre').on('click', '.genre-edit', function() {
    // $(".genre-edit").click(function(event){
        var publisher_id =  $(this).attr('value');
        swal({
            text: 'Input a new name of genre. e.g. "Action",...',
            content: "input",
            button: {
                text: "Edit Genre",
                cancel: "Cancel",
                closeModal: false,
            },
        }).then((value) => {
            if (value) {
                $.ajax({
                    url: "/admin/genre_update",
                    method: "POST",
                    dataType: "json",
                    data: {publisher_name: value, publisher: publisher_id},
                    error: function (xhr, status, error) {
                        console.error('AJAX Error: ' + status + error);
                        swal("Can not add!", {
                            icon: "error",
                        });
                    },
                    success: function (response) {
                        swal("Genres has been updated!", {
                            icon: "success",
                        });
                        $(".genre-name-"+ gpublisher_id).text(value);
                    }
                });

            }
        });
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

app/views/admin/users.html.erb
<h1>USER</h1>