config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :likes
  post 'likes/check_delete'
  get 'admin/genres'
  post 'admin/genre_delete'
  post 'admin/genre_add'
  post 'admin/genre_update'
  post 'admin/publisher_delete'
  post 'admin/publisher_add'
  post 'admin/publisher_update'
  get 'admin/publishers'
  get 'admin/games_in'
  get 'admin/create_game'
  post 'admin/game_delete'
  get 'admin/users'
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/genre_top'
  
  get 'home_page/index'
  get 'home_page/genre_top'

  resources :review_comments

  resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :games
  resources :genres
  resources :publishers
  devise_for :users, controllers: {
      registrations: 'users/registrations',
  }
  resources :users, except: [:edit] do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resource  :notifications, only: [:update] do
    post "seen_notification"
  end
  root :to => "home_page#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'rates' => 'rate#index'
  post 'rate' => 'rate#update'
  post 'search' => 'search#search'

  # for notifications
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    default_url_options :host => "localhost:3000"
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :check_exists_follow, only: [:destroy]
  def create
    @user = User.find(params[:followed_id])
    unless current_user.following?(@user)
      current_user.follow(@user)
      @notification = Notification.find_by from_user_id: @current_user.id, to_user_id: @user.id, type: Notification.types[:follow];
      if @notification
        @notification.update_attributes status: Notification.statuses[:not_seen]
      else
        @notification = Notification.new(
            from_user_id: @current_user.id,
            to_user_id: @user.id,
            type: Notification.types[:follow],
            review_id: -1,
            status: Notification.statuses[:not_seen]
        )
      end
      @notification.save
    end
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Follow.find(params[:id]).followed
    if current_user.following?(@user)
      current_user.unfollow(@user)
      @notification = Notification.find_by from_user_id: @current_user.id, to_user_id: @user.id, type: Notification.types[:follow], status: Notification.statuses[:not_seen]
      if @notification
        @notification.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  private
  def check_exists_follow
    if Follow.find_by(id: params[:id])
      true
    else
      false
    end
  end
end

app/views/relationships/_follow.html.erb
<%= form_for(current_user.active_relationships.build, url: relationships_path,  html: { method: :post }, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, user.id %></div>
    <%=  button_tag(type: 'submit', class: "btn btn-primary btn-labeled") do %>
        <span class="btn-label"><i class="fa fa-user-plus"></i></span> Follow
    <% end %>
<% end %>

app/views/relationships/_form_follow.html.erb
<% if !current_user?(user) %>
    <% if current_user.following?(user) %>
        <%= render "relationships/unfollow", user: user  %>
    <% else %>
        <%= render "relationships/follow", user: user   %>
    <%end%>
<% end %>

app/views/relationships/_form_following.html.erb
<li class="following-item">
  <div class="box-info">
    <%= image_tag following.avatar.url || "default-user.jpg", class: "avatar flex-item"%>
    <%= link_to user_path(following) do %>
      <h4 class="username"><%= following.name%></h4>
    <% end %>
  </div>
  <div class="flex-item">
    <%= render "relationships/form_follow", user: following%>
  </div>
</li>

app/views/relationships/_list_following.html.erb
<% followings = user.following %>
<ul class="list-following">
  <% followings.each do |following| %>
    <%= render "relationships/form_following", following: following%>
  <% end %>
</ul>

app/views/relationships/_unfollow.html.erb
<% relationship = current_user.active_relationships.find_by(followed_id: user.id)%>
<%= form_for(relationship, url: relationship_path(relationship.id),
             html: { method: :delete }, remote: true) do |f| %>
    <%=  button_tag(type: 'submit', class: "btn btn-default btn-labeled") do %>
        <span class="btn-label"><i class="fa fa-user-times" aria-hidden="true"></i></span> Unfollow
    <% end %>
<% end %>

app/views/relationships/create.js.erb
if($('.list-following').length) {
    $('.list-following').empty();
    $('.list-following').append(`<%= render("relationships/list_following", user: current_user)%>`);
    $('.number-followers').text('<%= current_user.followers.count%>');
    $('.number-following').text('<%= current_user.following.count%>');
} else if($('.form-follow').length) {
    $('.form-follow').empty();
    $('.form-follow').append(`<%= render("relationships/form_follow", user: @user)%>`);
    $('.number-followers').text('<%= @user.followers.count%>');
    $('.number-following').text('<%= @user.following.count%>');
}

app/views/relationships/destroy.js.erb
if($('.list-following').length) {
    $('.list-following').empty();
    $('.list-following').append(`<%= render("relationships/list_following", user: current_user)%>`);
    $('.number-followers').text('<%= current_user.followers.count%>');
    $('.number-following').text('<%= current_user.following.count%>');
} else if($('.form-follow').length) {
    $('.form-follow').empty();
    $('.form-follow').append(`<%= render("relationships/form_follow", user: @user)%>`);
    $('.number-followers').text('<%= @user.followers.count%>');
    $('.number-following').text('<%= @user.following.count%>');
}